version: '3.8'

services:
  coji-api:
    build: .
    command: gunicorn api:app -w 1 --threads 2 -b 0.0.0.0:8000
    volumes:
      - ./api:/app
    expose:
      - "8000"
    ports:
      - "8000:8000"
    restart: always
    env_file:
      - .env
    networks:
      - network

networks:
  network: { }